---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.1.1

platforms:
  - name: centos-6.5
    driver_config:
      network:
        - ["forwarded_port", {guest: 80, host: 8000}]
        - ["forwarded_port", {guest: 81, host: 8081}]

suites:
  - name: default
    run_list:
      - recipe[sample-app::default]
    attributes:
